version: "3.7"

services:
  snoopy:
    image: golang:latest
    container_name: snoopy
    entrypoint: /app/bin/entrypoint.sh
    privileged: yes
    environment:
      SNOOPY_PASSWORD: ${SNOOPY_PASSWORD}
    volumes:
      - "./:/app"
